version: '2'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-CU11
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password1
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
  php:
    build: docker/php
    environment:
      - ADMINER_DEFAULT_SERVER=mssql
      - ADMINER_PLUGINS=
      - ADMINER_DESIGN=
  nginx:
    build: docker/nginx
    ports:
      - "8080:80"